/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.unileste.projetofinal.gui;

/**
 *
 * @author geova
 */
public class ContaPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContaPanel
     */
    public ContaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        tituloConta = new javax.swing.JLabel();
        tituloNumeroConta = new javax.swing.JLabel();
        tituloTipoConta = new javax.swing.JLabel();
        tituloCpf = new javax.swing.JLabel();
        tituloSaldo = new javax.swing.JLabel();
        tituloLimiteChequeEspecial = new javax.swing.JLabel();
        tituloTaxaRendimentoMensal = new javax.swing.JLabel();
        txtNumeroConta = new javax.swing.JTextField();
        txtTipoConta = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        txtLimiteChequeEspecial = new javax.swing.JTextField();
        txtTaxaRendimentoMensal = new javax.swing.JTextField();
        btnAbrirConta = new javax.swing.JButton();
        btnBuscarConta = new javax.swing.JButton();
        btnListarContas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaContas = new javax.swing.JTable();

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 800));

        tituloConta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloConta.setText("Conta");
        tituloConta.setFocusable(false);
        tituloConta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tituloNumeroConta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloNumeroConta.setText("Número da conta:");

        tituloTipoConta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloTipoConta.setText("Tipo de Conta:");

        tituloCpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloCpf.setText("CPF:");

        tituloSaldo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloSaldo.setText("Saldo R$:");

        tituloLimiteChequeEspecial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloLimiteChequeEspecial.setText("Limite Cheque Especial:");

        tituloTaxaRendimentoMensal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloTaxaRendimentoMensal.setText("Taxa Rendimento Mensal:");

        txtLimiteChequeEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimiteChequeEspecialActionPerformed(evt);
            }
        });

        btnAbrirConta.setText("Abrir Conta");

        btnBuscarConta.setText("Buscar Conta");

        btnListarContas.setText("Listar Contas");

        tabelaContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Número Conta", "Tipo", "CPF - Proprietário", "Limite Cheque Especial", "Taxa Rendimento Mensal"
            }
        ));
        jScrollPane1.setViewportView(tabelaContas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(tituloConta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloNumeroConta)
                                    .addComponent(tituloTipoConta)
                                    .addComponent(tituloCpf)
                                    .addComponent(tituloSaldo))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumeroConta)
                                    .addComponent(txtTipoConta)
                                    .addComponent(txtCpf)
                                    .addComponent(txtSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(tituloTaxaRendimentoMensal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTaxaRendimentoMensal))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(tituloLimiteChequeEspecial)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtLimiteChequeEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnAbrirConta)
                .addGap(92, 92, 92)
                .addComponent(btnBuscarConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnListarContas)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tituloConta)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNumeroConta)
                    .addComponent(txtNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloTipoConta)
                    .addComponent(txtTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloSaldo)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloLimiteChequeEspecial)
                    .addComponent(txtLimiteChequeEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloTaxaRendimentoMensal)
                    .addComponent(txtTaxaRendimentoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrirConta)
                    .addComponent(btnBuscarConta)
                    .addComponent(btnListarContas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLimiteChequeEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimiteChequeEspecialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLimiteChequeEspecialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirConta;
    private javax.swing.JButton btnBuscarConta;
    private javax.swing.JButton btnListarContas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaContas;
    private javax.swing.JLabel tituloConta;
    private javax.swing.JLabel tituloCpf;
    private javax.swing.JLabel tituloLimiteChequeEspecial;
    private javax.swing.JLabel tituloNumeroConta;
    private javax.swing.JLabel tituloSaldo;
    private javax.swing.JLabel tituloTaxaRendimentoMensal;
    private javax.swing.JLabel tituloTipoConta;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtLimiteChequeEspecial;
    private javax.swing.JTextField txtNumeroConta;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTaxaRendimentoMensal;
    private javax.swing.JTextField txtTipoConta;
    // End of variables declaration//GEN-END:variables
}
